### ISSUE TITLE
Band limited / antialiased oscillators do not seem to work ( v2 )

### ISSUE THREAD

**Issue by JTriggerFish** [charlieroberts/gibber.audio.lib#15]
In Gibber v2, the following aliases audibly below the fundamental

Clock.bpm = 82
Theory.root = 'b2'
Theory.mode = 'ionian'
synth = Monosynth('pluck', {antialias:true})
synth.octave = 3
synth.note.seq([0,2,5], 1/4)

Setting antialias to true or false does not make a difference.

**Comment by charlieroberts** [comment]
fixed! Also, `pluck` doesn't seem to be a preset anymore, although `pluckEcho` is...

**Comment by JTriggerFish** [comment]
Hi @charlieroberts did you commit this somewhere ?
Using 'pluck' it makes no difference but that could be because it's not a valid preset, but with "pluckEcho" using antialias:true results in no sound at all.

**Comment by charlieroberts** [comment]
Sorry, you're right, I pushed the changes to the underlying audio engine but not to this repo.  They're pushed now... try the following:
```js
b = Synth({ antialias:1 })
b.note(14)
b.antialias = 0
b.note(14)
```
