### ISSUE TITLE
"short.dry" preset is inaccessible ( gh-pages / v2 )

### ISSUE THREAD

**Issue by JTriggerFish** [charlieroberts/gibber.audio.lib#16]
I think the quotes are an issue.

Also would you mind adding this 
'arpy' : {antialias:true,
    attack: audio => audio.Clock.ms(.5),
    decay: 1/16, gain:0.2,
    cutoff:.15,
    filterMult:1,
    Q:.3,
    filterType:1,
    filterMode:1}

as a monosynth preset ? Happy to do a pull request instead if you prefer but thought it might be easier this way.

Also should antialias:true be the default for all presets ? I was under the impression that at the moment the performance bottleneck is not the audio dsp but in the graph processing / generation.

Thank you !!

**Comment by charlieroberts** [comment]
Thanks! The problem with short.dry was that I was calling `Clock.ms(1) / 4`, but `Clock.ms()` actually returns an object... objects don't like to be divided.

Added `arpy` as a Monosynth preset. Gibber v1 had some easy ways to define / use custom presets; I should look into reinstating some of these.

**Comment by JTriggerFish** [comment]
super, thanks !
