### ISSUE TITLE
case inconsistency between PolySynth and Monosynth (gh-pages)

### ISSUE THREAD

**Issue by JTriggerFish** [charlieroberts/gibber.audio.lib#17]
Happy to fix it via a pull request unless you have any objections

**Comment by charlieroberts** [comment]
I don't have a good answer for this. In v1 Monosynth was simply Mono. I think it's confusing because a PolySynth isn't multiple Monosynth voices, it's multiple synth voices, while PolyMono is multiple Monosynth voices... I guess I could go with PolySynth and PolyMonosynth?

**Comment by charlieroberts** [comment]
or just Mono and PolyMono

**Comment by JTriggerFish** [comment]
Oh I see, I didn’t realise there were these additional subtleties.
It’s a minor point to be honest, might as well leave it and close this to be honest.
